// Package config loads/saves the agent YAML config and creates a default
// config (including GPU auto-detection) on `init`.
package config

import (
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/RunGPU-io/rungpu-agent/internal/gpu"
	"github.com/RunGPU-io/rungpu-agent/internal/types"
	"gopkg.in/yaml.v3"
)

const DefaultPoolURL = "https://rungpu-pool-api-420004393585.us-central1.run.app"

// DefaultConfigPath returns the cross-platform default config location:
// ~/.tokenize/config.yaml (Windows: %USERPROFILE%\.tokenize\config.yaml).
func DefaultConfigPath() string {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		home = "."
	}
	return filepath.Join(home, ".tokenize", "config.yaml")
}

// New builds a default config, auto-detecting local GPUs.
func New(apiKey string) (*types.Config, error) {
	machineID, err := randomUUID()
	if err != nil {
		return nil, fmt.Errorf("create machine identity: %w", err)
	}

	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		home = "."
	}

	cfg := &types.Config{
		APIKey:                apiKey,
		MachineID:             machineID,
		PoolURL:               DefaultPoolURL,
		PricePerMinute:        0.02,
		ModelCacheDir:         filepath.Join(home, ".tokenize", "models"),
		MaxModelCacheGB:       100,
		CleanupIntervalHours:  24,
		CustomAssetTTLDays:    7,
		MaxCustomAssetCacheGB: 20,
		HeartbeatIntervalSecs: 30,
		Metrics: types.MetricsConfig{
			EnableGPUMonitoring:    true,
			MonitoringIntervalSecs: 5,
		},
	}
	RefreshGPUIDs(cfg)
	ApplyDefaults(cfg)
	return cfg, nil
}

func randomUUID() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return formatUUID(b), nil
}

func formatUUID(b []byte) string {
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

func deterministicGPUID(machineID string, deviceIndex int) string {
	sum := sha256.Sum256([]byte(fmt.Sprintf("%s:%d", machineID, deviceIndex)))
	b := sum[:16]
	b[6] = (b[6] & 0x0f) | 0x50
	b[8] = (b[8] & 0x3f) | 0x80
	return formatUUID(b)
}

func RefreshGPUIDs(cfg *types.Config) {
	detected := gpu.Detect()
	count := len(detected)
	if count == 0 {
		count = 1
	}
	cfg.GPUIDs = make([]string, 0, count)
	for position := 0; position < count; position++ {
		deviceIndex := position
		if position < len(detected) {
			deviceIndex = detected[position].Index
		}
		cfg.GPUIDs = append(cfg.GPUIDs, deterministicGPUID(cfg.MachineID, deviceIndex))
	}
}

// Load reads and parses a config file. Warns if the file has insecure
// permissions (the config contains a machine-scoped credential).
func Load(path string) (*types.Config, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("config file not found at %s: %w", path, err)
	}

	// Check permissions on Unix — warn if group/other can read the credential.
	if mode := info.Mode().Perm(); mode&0o077 != 0 {
		fmt.Fprintf(os.Stderr,
			"WARNING: config file %s has permissions %o — should be 600 (contains a machine credential).\n"+
				"  Fix with: chmod 600 %s\n", path, mode, path)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("cannot read config at %s: %w", path, err)
	}
	var cfg types.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to parse config: %w", err)
	}
	return &cfg, nil
}

// Save writes the config to disk with helpful comments, creating parent
// directories as needed. The file is written with 0600 permissions since it
// contains the machine credential.
func Save(cfg *types.Config, path string) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	// Write a commented config so users can easily edit it.
	content := generateCommentedConfig(cfg)
	return os.WriteFile(path, []byte(content), 0o600)
}

// generateCommentedConfig produces a human-readable YAML config with inline
// documentation for every field. This is what `init` writes and what users edit.
func generateCommentedConfig(cfg *types.Config) string {
	gpuIDs := ""
	for _, id := range cfg.GPUIDs {
		gpuIDs += fmt.Sprintf("\n  - %q", id)
	}

	return fmt.Sprintf(`# ═══════════════════════════════════════════════════════════════════════════
# RunGPU Agent Configuration
# Generated by: rungpu-agent init
# Docs: https://www.rungpu.io/marketplace/host
# ═══════════════════════════════════════════════════════════════════════════

# ── Authentication ─────────────────────────────────────────────────────────
# Revocable credential for this enrolled machine. Never use an owner account
# key here. Override at runtime with RUNGPU_AGENT_KEY when managed externally.
api_key: %q

# Stable identity for this physical computer. Generated once; do not copy this
# config to another computer.
machine_id: %q

# ── Pool Connection ────────────────────────────────────────────────────────
# The RunGPU pool coordinator URL. The agent connects outbound over WebSocket.
# No inbound ports or public IP needed — works behind NAT/firewalls.
#   Production: https://rungpu-pool-api-420004393585.us-central1.run.app
#   Local dev:  http://localhost:3001
pool_url: %q

# ── GPU Configuration ─────────────────────────────────────────────────────
# Auto-detected GPU identifiers. Usually you don't need to change these.
gpu_ids:%s

# Which GPU device to expose to containers. Leave empty for all GPUs.
# On multi-GPU hosts, set to "0" or a GPU UUID to restrict to one device.
# Passed as: docker run --gpus device=<gpu_device>
gpu_device: %q

# Your listing price per GPU-minute in USD.
price_per_minute: %.4f

# ── Model Cache ────────────────────────────────────────────────────────────
# Where downloaded models are stored on disk. Models are cached so repeat
# jobs don't re-download. Needs fast storage (SSD recommended).
model_cache_dir: %q

# Maximum disk space for cached models (GB). Old models are cleaned up
# automatically when this limit is reached (LRU eviction).
max_model_cache_gb: %d

# How often to run cache cleanup (hours). Default: 24. Set to -1 to disable.
cleanup_interval_hours: %d

# Remove cached LoRAs, checkpoints, workflows, and stale job staging after this
# many days without use. Default: 7. Set to -1 to disable age-based removal.
custom_asset_ttl_days: %d

# Maximum combined size of cached LoRAs, checkpoints, and workflows (GB).
# When exceeded, least-recently-used assets are removed first. Set to -1 to
# disable the size budget while retaining TTL cleanup.
max_custom_asset_cache_gb: %d

# ── Agent Behavior ─────────────────────────────────────────────────────────
# How often to send heartbeats to the pool (seconds). The pool marks your
# GPU as offline if no heartbeat is received for 90 seconds.
heartbeat_interval_secs: %d

# Allow this machine to serve pool jobs without a detected GPU accelerator.
# Default: false. Enable only when CPU-backed Ollama inference is intentional.
allow_cpu_serving: %t

# Maximum runtime for a batch job (minutes) before the container is killed.
# 0 = default (60 minutes). Workspace jobs (ComfyUI, Jupyter) are not affected.
job_timeout_minutes: %d

# Maximum size for a single custom file download — LoRA, checkpoint, etc. (GB).
# 0 = unlimited. Recommended: 10-20 GB to prevent abuse.
max_custom_file_gb: %d

# ── GPU Monitoring ─────────────────────────────────────────────────────────
metrics:
  # Enable real-time GPU monitoring (temperature, utilization, memory).
  enable_gpu_monitoring: %t

  # How often to collect GPU metrics (seconds).
  monitoring_interval_secs: %d

# ── Security ───────────────────────────────────────────────────────────────
# These settings control what renters can run on your machine.
# You can also manage these from the web dashboard.
security:
  # DANGER: If true, allows ANY Docker image (not just trusted registries).
  # Only enable if you trust all renters. Default: false.
  allow_any_image: %t

  # Additional Docker registries this host explicitly trusts.
  # Example: ["myregistry.com/", "ghcr.io/my-org/"]
  trusted_registries: []

  # Container memory limit in GB. 0 = no limit.
  # Recommended: your GPU VRAM + 16 GB (for system overhead).
  max_memory_gb: %d

  # Container CPU limit. 0 = no limit.
  # Recommended: half your CPU cores.
  max_cpus: %.1f

  # DANGER: If true, containers run with --network host (full network access).
  # Default: false (containers are network-isolated on Docker bridge).
  allow_host_network: %t

# For gated models, provide HF_TOKEN in the agent process environment.
# Tokens are intentionally never stored in this file.
`,
		cfg.APIKey,
		cfg.MachineID,
		cfg.PoolURL,
		gpuIDs,
		cfg.GPUDevice,
		cfg.PricePerMinute,
		cfg.ModelCacheDir,
		cfg.MaxModelCacheGB,
		cfg.CleanupIntervalHours,
		cfg.CustomAssetTTLDays,
		cfg.MaxCustomAssetCacheGB,
		cfg.HeartbeatIntervalSecs,
		cfg.AllowCPUServing,
		cfg.JobTimeoutMinutes,
		cfg.MaxCustomFileGB,
		cfg.Metrics.EnableGPUMonitoring,
		cfg.Metrics.MonitoringIntervalSecs,
		cfg.Security.AllowAnyImage,
		cfg.Security.MaxMemoryGB,
		cfg.Security.MaxCPUs,
		cfg.Security.AllowHostNetwork,
	)
}

// ApplyDefaults fills in any missing fields with sensible defaults so a
// minimal config (just api_key) is enough to start the agent.
func ApplyDefaults(cfg *types.Config) {
	if key := strings.TrimSpace(os.Getenv("RUNGPU_AGENT_KEY")); key != "" {
		cfg.APIKey = key
	}
	if token := strings.TrimSpace(os.Getenv("HF_TOKEN")); token != "" {
		cfg.Security.HFToken = token
	}
	if cfg.MachineID == "" {
		machineID, err := randomUUID()
		if err == nil {
			cfg.MachineID = machineID
		}
	}
	if cfg.PoolURL == "" {
		cfg.PoolURL = DefaultPoolURL
	}
	if len(cfg.GPUIDs) == 0 {
		RefreshGPUIDs(cfg)
	}
	if cfg.PricePerMinute == 0 && !cfg.ContributeFree {
		cfg.PricePerMinute = 0.02
	}
	if cfg.ModelCacheDir == "" {
		home, _ := os.UserHomeDir()
		if home == "" {
			home = "."
		}
		cfg.ModelCacheDir = filepath.Join(home, ".tokenize", "models")
	}
	if cfg.MaxModelCacheGB == 0 {
		cfg.MaxModelCacheGB = 100
	}
	if cfg.CleanupIntervalHours == 0 {
		cfg.CleanupIntervalHours = 24
	}
	if cfg.CustomAssetTTLDays == 0 {
		cfg.CustomAssetTTLDays = 7
	}
	if cfg.MaxCustomAssetCacheGB == 0 {
		cfg.MaxCustomAssetCacheGB = 20
	}
	if cfg.HeartbeatIntervalSecs == 0 {
		cfg.HeartbeatIntervalSecs = 30
	}
	if cfg.JobTimeoutMinutes <= 0 {
		cfg.JobTimeoutMinutes = 60
	}
	if cfg.MaxCustomFileGB <= 0 {
		cfg.MaxCustomFileGB = 20
	}
	system := gpu.DetectSystem()
	if cfg.Security.MaxMemoryGB <= 0 {
		cfg.Security.MaxMemoryGB = int(system.RAMTotalGB * 0.8)
		if cfg.Security.MaxMemoryGB < 4 {
			cfg.Security.MaxMemoryGB = 4
		}
	}
	if cfg.Security.MaxCPUs <= 0 {
		cfg.Security.MaxCPUs = float64(system.CPUCores) / 2
		if cfg.Security.MaxCPUs < 1 {
			cfg.Security.MaxCPUs = 1
		}
	}
	if !cfg.Metrics.EnableGPUMonitoring && cfg.Metrics.MonitoringIntervalSecs == 0 {
		cfg.Metrics.EnableGPUMonitoring = true
		cfg.Metrics.MonitoringIntervalSecs = 5
	}
}

// Validate checks required fields.
func Validate(cfg *types.Config) error {
	if cfg.APIKey == "" {
		return fmt.Errorf("machine credential is empty — enroll this host or set RUNGPU_AGENT_KEY")
	}
	// Auto-fill everything else so a minimal config works.
	ApplyDefaults(cfg)
	return nil
}
