// Package config loads/saves the agent YAML config and creates a default
// config (including GPU auto-detection) on `init`.
package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/RunGPU-io/gpu-agent/internal/gpu"
	"github.com/RunGPU-io/gpu-agent/internal/types"
	"gopkg.in/yaml.v3"
)

// DefaultConfigPath returns the cross-platform default config location:
// ~/.tokenize/config.yaml (Windows: %USERPROFILE%\.tokenize\config.yaml).
func DefaultConfigPath() string {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		home = "."
	}
	return filepath.Join(home, ".tokenize", "config.yaml")
}

// New builds a default config, auto-detecting local GPUs.
func New(apiKey string) (*types.Config, error) {
	gpus := gpu.Detect()

	gpuIDs := make([]string, 0, len(gpus))
	for _, g := range gpus {
		gpuIDs = append(gpuIDs, fmt.Sprintf("gpu-%d", g.Index))
	}

	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		home = "."
	}

	return &types.Config{
		APIKey:                apiKey,
		PoolURL:               "https://pool.rungpu.io",
		GPUIDs:                gpuIDs,
		PricePerMinute:        0.02,
		ModelCacheDir:         filepath.Join(home, ".tokenize", "models"),
		MaxModelCacheGB:       100,
		CleanupIntervalHours:  24,
		HeartbeatIntervalSecs: 30,
		Metrics: types.MetricsConfig{
			EnableGPUMonitoring:    true,
			MonitoringIntervalSecs: 5,
		},
	}, nil
}

// Load reads and parses a config file. Warns if the file has insecure
// permissions (the config contains the API key).
func Load(path string) (*types.Config, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("config file not found at %s: %w", path, err)
	}

	// Check permissions on Unix — warn if group/other can read (API key exposure)
	if mode := info.Mode().Perm(); mode&0o077 != 0 {
		fmt.Fprintf(os.Stderr,
			"WARNING: config file %s has permissions %o — should be 600 (contains API key).\n"+
				"  Fix with: chmod 600 %s\n", path, mode, path)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("cannot read config at %s: %w", path, err)
	}
	var cfg types.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to parse config: %w", err)
	}
	return &cfg, nil
}

// Save writes the config to disk with helpful comments, creating parent
// directories as needed. The file is written with 0600 permissions since it
// contains the API key.
func Save(cfg *types.Config, path string) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	// Write a commented config so users can easily edit it.
	content := generateCommentedConfig(cfg)
	return os.WriteFile(path, []byte(content), 0o600)
}

// generateCommentedConfig produces a human-readable YAML config with inline
// documentation for every field. This is what `init` writes and what users edit.
func generateCommentedConfig(cfg *types.Config) string {
	gpuIDs := ""
	for _, id := range cfg.GPUIDs {
		gpuIDs += fmt.Sprintf("\n  - %q", id)
	}

	return fmt.Sprintf(`# ═══════════════════════════════════════════════════════════════════════════
# RunGPU Agent Configuration
# Generated by: rungpu-agent init
# Docs: https://www.rungpu.io/marketplace/host
# ═══════════════════════════════════════════════════════════════════════════

# ── Authentication ─────────────────────────────────────────────────────────
# Your API key from the RunGPU dashboard. Keep this secret.
# Get a new key: https://www.rungpu.io/marketplace/host
api_key: %q

# ── Pool Connection ────────────────────────────────────────────────────────
# The RunGPU pool coordinator URL. The agent connects outbound over WebSocket.
# No inbound ports or public IP needed — works behind NAT/firewalls.
#   Production: https://pool.rungpu.io
#   Local dev:  http://localhost:3001
pool_url: %q

# ── GPU Configuration ─────────────────────────────────────────────────────
# Auto-detected GPU identifiers. Usually you don't need to change these.
gpu_ids:%s

# Which GPU device to expose to containers. Leave empty for all GPUs.
# On multi-GPU hosts, set to "0" or a GPU UUID to restrict to one device.
# Passed as: docker run --gpus device=<gpu_device>
gpu_device: %q

# Your price per GPU-minute in USD. You earn 85%% of this; 15%% is the
# platform fee. Set competitively — check marketplace for current rates.
price_per_minute: %.4f

# ── Model Cache ────────────────────────────────────────────────────────────
# Where downloaded models are stored on disk. Models are cached so repeat
# jobs don't re-download. Needs fast storage (SSD recommended).
model_cache_dir: %q

# Maximum disk space for cached models (GB). Old models are cleaned up
# automatically when this limit is reached (LRU eviction).
max_model_cache_gb: %d

# How often to run cache cleanup (hours). Set to 0 to disable.
cleanup_interval_hours: %d

# ── Agent Behavior ─────────────────────────────────────────────────────────
# How often to send heartbeats to the pool (seconds). The pool marks your
# GPU as offline if no heartbeat is received for 90 seconds.
heartbeat_interval_secs: %d

# Maximum runtime for a batch job (minutes) before the container is killed.
# 0 = default (60 minutes). Workspace jobs (ComfyUI, Jupyter) are not affected.
job_timeout_minutes: %d

# Maximum size for a single custom file download — LoRA, checkpoint, etc. (GB).
# 0 = unlimited. Recommended: 10-20 GB to prevent abuse.
max_custom_file_gb: %d

# ── GPU Monitoring ─────────────────────────────────────────────────────────
metrics:
  # Enable real-time GPU monitoring (temperature, utilization, memory).
  enable_gpu_monitoring: %t

  # How often to collect GPU metrics (seconds).
  monitoring_interval_secs: %d

# ── Security ───────────────────────────────────────────────────────────────
# These settings control what renters can run on your machine.
# You can also manage these from the web dashboard.
security:
  # DANGER: If true, allows ANY Docker image (not just trusted registries).
  # Only enable if you trust all renters. Default: false.
  allow_any_image: %t

  # Additional trusted Docker registries beyond the built-in list.
  # Built-in: ghcr.io/tokenize/, ghcr.io/ai-dock/, registry.hf.space/,
  #           docker.io/library/, jupyter/, pytorch/, nvcr.io/nvidia/
  # Example: ["myregistry.com/", "ghcr.io/my-org/"]
  trusted_registries: []

  # Container memory limit in GB. 0 = no limit.
  # Recommended: your GPU VRAM + 16 GB (for system overhead).
  max_memory_gb: %d

  # Container CPU limit. 0 = no limit.
  # Recommended: half your CPU cores.
  max_cpus: %.1f

  # DANGER: If true, containers run with --network host (full network access).
  # Default: false (containers are network-isolated on Docker bridge).
  allow_host_network: %t

  # HuggingFace access token for downloading gated models (e.g. Llama 3).
  # Get yours at: https://huggingface.co/settings/tokens
  # Leave empty if you don't need gated model access.
  hf_token: %q
`,
		cfg.APIKey,
		cfg.PoolURL,
		gpuIDs,
		cfg.GPUDevice,
		cfg.PricePerMinute,
		cfg.ModelCacheDir,
		cfg.MaxModelCacheGB,
		cfg.CleanupIntervalHours,
		cfg.HeartbeatIntervalSecs,
		cfg.JobTimeoutMinutes,
		cfg.MaxCustomFileGB,
		cfg.Metrics.EnableGPUMonitoring,
		cfg.Metrics.MonitoringIntervalSecs,
		cfg.Security.AllowAnyImage,
		cfg.Security.MaxMemoryGB,
		cfg.Security.MaxCPUs,
		cfg.Security.AllowHostNetwork,
		cfg.Security.HFToken,
	)
}

// ApplyDefaults fills in any missing fields with sensible defaults so a
// minimal config (just api_key) is enough to start the agent.
func ApplyDefaults(cfg *types.Config) {
	if cfg.PoolURL == "" {
		cfg.PoolURL = "https://pool.rungpu.io"
	}
	if len(cfg.GPUIDs) == 0 {
		gpus := gpu.Detect()
		for _, g := range gpus {
			cfg.GPUIDs = append(cfg.GPUIDs, fmt.Sprintf("gpu-%d", g.Index))
		}
	}
	if cfg.PricePerMinute == 0 {
		cfg.PricePerMinute = 0.02
	}
	if cfg.ModelCacheDir == "" {
		home, _ := os.UserHomeDir()
		if home == "" {
			home = "."
		}
		cfg.ModelCacheDir = filepath.Join(home, ".tokenize", "models")
	}
	if cfg.MaxModelCacheGB == 0 {
		cfg.MaxModelCacheGB = 100
	}
	if cfg.CleanupIntervalHours == 0 {
		cfg.CleanupIntervalHours = 24
	}
	if cfg.HeartbeatIntervalSecs == 0 {
		cfg.HeartbeatIntervalSecs = 30
	}
	if !cfg.Metrics.EnableGPUMonitoring && cfg.Metrics.MonitoringIntervalSecs == 0 {
		cfg.Metrics.EnableGPUMonitoring = true
		cfg.Metrics.MonitoringIntervalSecs = 5
	}
}

// Validate checks required fields.
func Validate(cfg *types.Config) error {
	if cfg.APIKey == "" {
		return fmt.Errorf("api_key is empty — set it in %s or run: rungpu-agent init --api-key YOUR_KEY", DefaultConfigPath())
	}
	// Auto-fill everything else so a minimal config works.
	ApplyDefaults(cfg)
	return nil
}
